// ADD PLAN
export const ADD_PLAN_REQUEST = "ADD_PLAN_REQUEST";
export const ADD_PLAN_SUCCESS = "ADD_PLAN_SUCCESS";
export const ADD_PLAN_FAILURE = "ADD_PLAN_FAILURE";
// FETCH PLANS
export const FETCH_PLANS_REQUEST = "FETCH_PLAN_REQUEST";
export const FETCH_PLANS_SUCCESS = "FETCH_PLAN_SUCCESS";
export const FETCH_PLANS_FAILURE = "FETCH_PLAN_FAILURE";
// UPDATE PLAN
export const UPDATE_PLAN_REQUEST = "UPDATE_PLAN_REQUEST";
export const UPDATE_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";
export const UPDATE_PLAN_FAILURE = "UPDATE_PLAN_FAILURE";
// DELETE PLAN
export const DELETE_PLAN_REQUEST = "DELETE_PLAN_REQUEST";
export const DELETE_PLAN_SUCCESS = "DELETE_PLAN_SUCCESS";
export const DELETE_PLAN_FAILURE = "DELETE_PLAN_FAILURE";
// SELECT PLAN
export const SELECT_PLAN = "SELECT_PLAN";
// ITEMS
export const ADD_ITEM_TO_PLAN = "ADD_ITEM_TO_PLAN";
export const UPDATE_ITEM_IN_PLAN = "UPDATE_ITEM_IN_PLAN";
export const DELETE_ITEM_IN_PLAN = "DELETE_ITEM_IN_PLAN";
